server:
  port: 5797
  tomcat:
    # 파트 개수 제한 해제(-1: 무제한)
    max-part-count: -1
    # 폼 필드(파라미터) 개수 제한
    max-parameter-count: 20000
    # 요청 본문 크기 제한 해제
    max-swallow-size: -1
    
# Oracle Connect
spring:
# Datasource Bean 생성
  datasource:
   driver-class-name: oracle.jdbc.driver.OracleDriver
#   url: jdbc:oracle:thin:@localhost:1521/xe
   url: jdbc:oracle:thin:@localhost:1521/xe
   username: s202507b
   password: tiger

  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
      file-size-threshold: -1 # 파일 크기 임계값 설정 (이 크기를 초과하면 디스크에 저장)
  
  #Jpa Setting
  jpa:
    # database-platform: org.hibernate.dialect.OracleDialect  # Jpa사용시 11g에 대한 방언 설정 --> Paging 작업 
    show-sql: true
    hibernate:
      ddl-auto: update
 
  # View Resolver --> jsp
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  # gmail Transfer 
  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true  
          
spring.servlet.multipart.max-file-size: 10MB
spring.servlet.multipart.max-request-size: 50MB

logging.level:
  org.hibernate.SQL: debug   # logger를 통해 하이버네이트 실행 SQL 
  
# Mybatis
mybatis:
  config-location: classpath:configuration.xml
#upload Folder
com.WiseForce.AssemERP.upload.path: upload
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
              